persistence true
persistence_location /mosquitto/data/
per_listener_settings false

log_dest stdout
log_type error
log_type warning
log_type notice
log_type information

listener 8883 0.0.0.0
protocol mqtt
cafile /mosquitto/data/runtime/ca.crt
certfile /mosquitto/data/runtime/server.crt
keyfile /mosquitto/data/runtime/server.key
require_certificate false
allow_anonymous false
tls_version tlsv1.2
message_size_limit 4096
max_connections 100

plugin /usr/lib/mosquitto_dynamic_security.so
plugin_opt_config_file /mosquitto/data/dynamic-security.json
